version: "3.9"

services:
    web:
        container_name: web
        build: .
        restart: on-failure
        command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 9999:8000
        depends_on:
            - db

    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=kampanyeku
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
        - pgdata:/var/lib/postgress/data

volumes:
    pgdata:
